name: Reusable Tests

on:
    workflow_call:

permissions:
    contents: read

jobs:
    test-ts:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout 🛒
              uses: actions/checkout@v6
            - name: node 22 ❇️
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'npm'
            - name: install dependencies 📦
              run: npm ci
            - name: lint 🧹
              run: npm run lint
            - name: tests 🧪
              run: npm run test
            - name: build 📦
              run: npm run build
